### ISSUE TITLE
The cPickle is missing

### ISSUE THREAD

**Issue by kookma** [stromatolith/RP_Bubble#1]
The cPickle is missing?

**Comment by stromatolith** [comment]
Hi Mohammad, in the lib there are the two functions "pickle_self" and "unpickle_thing". In the plot_01 code the calculation results are conserved by storing them in the pickled objects (line 37), so in the plot_02 code it can be avoided to have to wait for the lengthy calculation to get executed. You have to run the plot_01 code once, in order to get the large data files which the plot_02 code can exploit. Did you try? Does it run on your machine? Sth like a year ago was the last time I had it running on one of my machines and the calculation takes a few minutes. On my older laptop it took over 25 minutes. You can increase the time steps and decrease the simulation period for quick checking until the code runs. Sincerely, Markus.

**Comment by kookma** [comment]
Hi Markus,
 Yes I run the plot_01 with no luck.

See line 28 of library
`from cPickle import Pickler, Unpickler`

When you run the code e.g plot_01  python returns an error as below

```

  File "G:\04.Python\2019\RP_Bubble-master\RP_lib.py", line 28, in <module>
    from cPickle import Pickler, Unpickler

ModuleNotFoundError: No module named 'cPickle'

```

So, It seems something is missing!

--Mohammad

**Comment by stromatolith** [comment]
I've always worked with Python 2.7.x. Are you working with Python 3? It seems cPickle is not part of the Standard Library in Python 3. It might be a quick solution to just switch from cPickle to Pickle, as both modules seem to have similar dump and load functions. Then of course, you'd have to pay attention also to other aspects of modifying/updating a Python 2 code to run in Python 3. For me personally, learning to deal with Python 3 is still on the ToDo side, so I can't be a great help with that at the moment ... maybe later this year it becomes unavoidable. In principle, you can also completely erase the pickling feature from the code, it's just a time-saving strategy for avoiding repeated identical calculations.

**Comment by stromatolith** [comment]
closing this issue; cPickle is part of the Python2 Standard Library; the availability of cPickle is a requirement to run the code in the given form;

(additional notes: users who want to start playing with this bubble simulator, can copy the tasks of the 2nd and 3rd script into the first script if intending to avoid the use of any pickling (i.e. object serialisation & storage); one can also replace cPickle with alternative serialisation tools; it cannot and should not be the task of the provider of an exemplary physics-illustrating code to equip the code with all kinds of backend alternatives of low-level functions based on speculating about many thinkable python environments)

**Comment by kookma** [comment]
Thanks Markus!
Yes, I use Python 3.
